version: "2"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "9411:9411"
      - "16686:16686"
  nginx:
    image: opentracing/nginx-opentracing
    volumes:
      - ./nginx-confs/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-confs/jaeger-config.json:/etc/jaeger-config.json
    ports:
      - "8000:80"
  backend:
    build: ./backend
    image: backend-otel
