version: "3.9"
services:
  user:
    container_name: bugs
    build: ./bugs
    ports:
      - 12345:12345
    environment:
      - OTEL_PYTHON_TRACER_PROVIDER=sdk_tracer_provider
      - OTEL_TRACES_EXPORTER=jaeger_thrift
      - OTEL_SERVICE_NAME=bugs-service
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_METRICS_EXPORTER=none

  todo:
    container_name: notes
    build: ./notes
    ports:
      - 23456:23456
    environment:
      - OTEL_TRACES_EXPORTER=jaeger_thrift
      - OTEL_SERVICE_NAME=notes-service
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_METRICS_EXPORTER=none

  redis:
    container_name: redis 
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - REDIS_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes

  mongo:
    image: mongo
    container_name: mongo 
    ports:
      - 27017:27017
    restart: unless-stopped

  jaeger:
    image: "jaegertracing/all-in-one:latest"
    container_name: jaeger
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
